name: loginandsignup
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fancy_bottom_navigation: ^0.3.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_core: ^0.2.5+1
  firebase_auth: ^0.6.6
  firebase_database: ^1.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  font_awesome_flutter: ^8.0.1

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - assets/email.png
    - assets/flutter-icon.png
    - assets/dark_grunge_bk.jpg
  fonts:
  - family: mermaid
    fonts:
    - asset: assets/Mermaid1001.ttf
  - family: bebas-neue
    fonts:
    - asset: assets/BebasNeue-Regular.ttf
  - family: biosan
    fonts:
    - asset: assets/biosans.ttf
  - family: CustomIcons
    fonts:
    - asset: assets/custom_icons.ttf
  - family: oscine
    fonts:
    - asset: assets/oscine.otf
  - family: oscinebold
    fonts:
    - asset: assets/oscinebold.otf